// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sskrqukxeeahnvfcdtum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNza3JxdWt4ZWVhaG52ZmNkdHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDIxODUsImV4cCI6MjA2NjIxODE4NX0.8oVsovyiVoG2xA6xoAuQiEOvb6OF7_N41DkFfQ5uzWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);